---
all:
  children:
    linux_snapshot_targets:
      children:
        linux_snapshot_t1:
          hosts:
            app-t1-01.example.local:
              cluster_name: Cluster-A
              vm_folder: /Cluster-A/vm/AppTier
            app-t1-02.example.local:
              cluster_name: Cluster-A
              vm_folder: /Cluster-A/vm/AppTier
            db-t1-01.example.local:
              cluster_name: Cluster-A
              vm_folder: /Cluster-A/vm/Database
        linux_snapshot_t0:
          hosts:
            app-t0-01.example.local:
              cluster_name: Cluster-B
              vm_folder: /Cluster-B/vm/AppTier
            db-t0-01.example.local:
              cluster_name: Cluster-B
              vm_folder: /Cluster-B/vm/Database
            integration-t0-01.example.local:
              cluster_name: Cluster-B
