---
all:
  children:
    linux_cis:
      children:
        debian12:
          hosts:
            debian12-node1:
              ansible_host: 192.0.2.10
        oracle_linux:
          hosts:
            oraclelinux-node1:
              ansible_host: 192.0.2.11
    linux_vm_setup_targets:
      children:
        linux_vm_setup_t0:
          children:
            oracle_linux:
        linux_vm_setup_t1:
          children:
            debian12:
        linux_vm_setup_t2:
          hosts: {}
